# Nombre del workflow que aparecerá en la pestaña "Actions"
name: 'Generar Informe Manualmente'

on:
  workflow_dispatch:

jobs:
  generate-report-only:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Descarga una copia de tu repositorio
      - name: 1. Descargar el código del repositorio
        uses: actions/checkout@v4

      # Paso 2: Configura el entorno de Python
      - name: 2. Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Paso 3: Instala las librerías ANTES de usarlas
      - name: 3. Instalar las librerías necesarias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4 (DEBUG): Ahora sí podrá leer el archivo porque ya tiene pandas
      - name: 'DEBUG: Verificar qué archivos y commits ve el robot'
        run: |
          echo "--- 1. Mostrando el commit que se está usando ---"
          git log -n 1
          echo "--- 2. Listando los archivos descargados ---"
          ls -lR
          echo "--- 3. Leyendo las últimas filas del Excel con Python (ruta corregida) ---"
          # Usamos la ruta correcta sin la carpeta
          python -c "import pandas as pd; df = pd.read_excel('Comentarios Campaña.xlsx'); print('El archivo tiene', len(df), 'filas en total.'); print('--- MOSTRANDO LAS ÚLTIMAS 10 FILAS ---'); print(df.tail(10))"

      # Paso 5: Ejecuta tu script principal
      - name: 5. Ejecutar SÓLO la generación del informe
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
        run: python generar_informe.py
