# Nombre del workflow que aparecerá en la pestaña "Actions"
name: 'Generar Informe Manualmente'

# Define que este workflow solo se puede activar manualmente
on:
  workflow_dispatch:

jobs:
  generate-report-only:
    # El tipo de máquina virtual en la que se ejecutará
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descarga una copia de tu repositorio en la máquina virtual
      - name: 1. Descargar el código del repositorio
        uses: actions/checkout@v4

      # Paso 2 (NUEVO): Paso de diagnóstico para ver qué está usando el robot
      - name: 'DEBUG: Verificar qué archivos y commits ve el robot'
        run: |
          echo "--- 1. Mostrando el commit que se está usando ---"
          git log -n 1

          echo "--- 2. Listando los archivos descargados (recursivamente) ---"
          ls -lR

          echo "--- 3. Leyendo las últimas filas del Excel con Python ---"
          # Este comando es la prueba definitiva. Nos dirá el contenido real del archivo.
          # Asegúrate de que la ruta 'dashboard-Mochisaurios/Comentarios Campaña.xlsx' es correcta.
          python -c "import pandas as pd; df = pd.read_excel('dashboard-Mochisaurios/Comentarios Campaña.xlsx'); print('El archivo tiene', len(df), 'filas en total.'); print('--- MOSTRANDO LAS ÚLTIMAS 10 FILAS ---'); print(df.tail(10))"

      # Paso 3: Configura el entorno de Python
      - name: 3. Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Paso 4: Instala las librerías de Python desde tu archivo requirements.txt
      - name: 4. Instalar las librerías necesarias
        run: |
          python -m pip install --upgrade pip
          # Asegúrate de que pandas y openpyxl estén en tu requirements.txt
          pip install -r requirements.txt

      # Paso 5: Ejecuta tu script para generar el informe
      - name: 5. Ejecutar SÓLO la generación del informe
        env:
          # Si tu script necesita secrets (tokens, etc.), se declaran aquí
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
        run: python generar_informe.py
